#!/usr/bin/sh

if [ ! -f "/home/meme/scripts/docker_test" ]; then
  echo "ERROR: To test the MEME Suite, you must run Docker from the 'tests' directory "
  echo "of a locally-installed version of the MEME Suite."
  echo "Please restart the container from that directory."
  exit 1
fi

if [ `pwd` != "/home/meme/scripts" ]; then
  echo "ERROR: You must run docker_test from the '/home/meme/scripts' directory."
  echo "Please rerun docker_test from that directory."
  exit 1
fi

# set higher for debugging
first=1

i=0
for fn in $(ls -1 *.test); do 
  # remove extension
  pgm=${fn%.*}

  # obsolete programs
  if [[ "$pgm" == "clustalw2fasta" || "$pgm" == "fasta-io" || "$fn" == "mhmm"* || "$pgm" == "shadow" ]]; then
    continue
  fi

  # announce program
  i=$((i+1));
  echo "$i $fn $pgm";

  # for quicker debugging
  if (( $i < first )) ; then 
    continue
  fi

  # name mismatch problem
  if [ "$pgm" = "create_priors" ]; then 
    pgm="create-priors" 
  fi
  if [ "$pgm" = "pspgen" ]; then 
    pgm="psp-gen" 
  fi

  # libexec problems
  if ! [[ -f "/opt/meme/bin/$pgm" || -h "/opt/meme/bin/$pgm" ]] ; then
    ln -s /opt/meme/libexec/meme-5.5.5/$pgm /opt/meme/bin
  fi

  # add getsize to bin; needed by meme-chip and xstreme
  if ! [ -f "/opt/meme/bin/getsize" ] ; then 
    ln -s /opt/meme/libexec/meme-5.5.5/getsize /opt/meme/bin
  fi

  # add meme2images to bin; needed by motif-in test
  if ! [ -f "/opt/meme/bin/meme2images" ] ; then 
    ln -s /opt/meme/libexec/meme-5.5.5/meme2images /opt/meme/bin
  fi

  # add "src" subdir link in DOCKER_BIN, pointing at DOCKER_BIN
  # needed by motif-in test
  if ! [ -h "/opt/meme/bin/src" ] ; then 
    ln -s /opt/meme/bin /opt/meme/bin/src
  fi

  # run test!
  if [ "$pgm" = "motif-in" ]; then
    # skip comprehensive for motif-in.test
    ./docker_test_driver $fn
  else
   ./docker_test_driver --comprehensive $fn
  fi

done
